
export type Currency = {
  code: string;
  name: string;
};

export const currencies: Currency[] = [
  { code: "USD", name: "US Dollar" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "British Pound" },
  { code: "JPY", name: "Japanese Yen" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "CNY", name: "Chinese Yuan" },
  { code: "HKD", name: "Hong Kong Dollar" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "KRW", name: "South Korean Won" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "INR", name: "Indian Rupee" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "ZAR", name: "South African Rand" },
  { code: "TRY", name: "Turkish Lira" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "TWD", name: "Taiwan Dollar" },
  { code: "DKK", name: "Danish Krone" },
  { code: "PLN", name: "Polish Zloty" },
  { code: "THB", name: "Thai Baht" },
  { code: "IDR", name: "Indonesian Rupiah" },
  { code: "HUF", name: "Hungarian Forint" },
  { code: "CZK", name: "Czech Koruna" },
  { code: "ILS", name: "Israeli Shekel" },
  { code: "CLP", name: "Chilean Peso" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "AED", name: "UAE Dirham" },
  { code: "COP", name: "Colombian Peso" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "RON", name: "Romanian Leu" },
  { code: "VND", name: "Vietnamese Dong" },
  { code: "BDT", name: "Bangladeshi Taka" },
  { code: "PKR", name: "Pakistani Rupee" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "ARS", name: "Argentine Peso" },
  { code: "NGN", name: "Nigerian Naira" },
  { code: "UAH", name: "Ukrainian Hryvnia" },
  { code: "QAR", name: "Qatari Riyal" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "DZD", name: "Algerian Dinar" },
  { code: "KZT", name: "Kazakhstani Tenge" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "MAD", name: "Moroccan Dirham" },
  { code: "BHD", name: "Bahraini Dinar" },
  { code: "OMR", name: "Omani Rial" },
  { code: "UYU", name: "Uruguayan Peso" },
  { code: "CRC", name: "Costa Rican Colón" },
  { code: "BGN", name: "Bulgarian Lev" },
  { code: "PEN", name: "Peruvian Sol" },
  { code: "GEL", name: "Georgian Lari" },
  { code: "XAF", name: "Central African CFA Franc" },
  { code: "LKR", name: "Sri Lankan Rupee" },
  { code: "TND", name: "Tunisian Dinar" },
  { code: "UZS", name: "Uzbekistani Som" },
  { code: "XOF", name: "West African CFA Franc" },
  { code: "KES", name: "Kenyan Shilling" },
  { code: "ETB", name: "Ethiopian Birr" },
  { code: "BOB", name: "Bolivian Boliviano" },
  { code: "HRK", name: "Croatian Kuna" },
  { code: "ISK", name: "Icelandic Króna" },
  { code: "GHS", name: "Ghanaian Cedi" },
  { code: "AMD", name: "Armenian Dram" },
  { code: "JMD", name: "Jamaican Dollar" },
  { code: "ALL", name: "Albanian Lek" },
  { code: "MUR", name: "Mauritian Rupee" },
  { code: "NPR", name: "Nepalese Rupee" },
  { code: "MKD", name: "Macedonian Denar" },
  { code: "RSD", name: "Serbian Dinar" },
  { code: "TTD", name: "Trinidad and Tobago Dollar" },
  { code: "TZS", name: "Tanzanian Shilling" },
  { code: "DOP", name: "Dominican Peso" },
  { code: "PYG", name: "Paraguayan Guaraní" },
  { code: "IRR", name: "Iranian Rial" },
  { code: "HTG", name: "Haitian Gourde" },
  { code: "BAM", name: "Bosnia and Herzegovina Convertible Mark" },
  { code: "ZMW", name: "Zambian Kwacha" },
  { code: "LAK", name: "Lao Kip" },
  { code: "MNT", name: "Mongolian Tögrög" },
  { code: "NAD", name: "Namibian Dollar" },
  { code: "MMK", name: "Myanmar Kyat" },
  { code: "SYP", name: "Syrian Pound" },
  { code: "AZN", name: "Azerbaijani Manat" },
  { code: "MZN", name: "Mozambican Metical" },
  { code: "MOP", name: "Macanese Pataca" },
  { code: "KHR", name: "Cambodian Riel" },
  { code: "MDL", name: "Moldovan Leu" },
  { code: "BZD", name: "Belize Dollar" },
  { code: "PAB", name: "Panamanian Balboa" },
  { code: "GMD", name: "Gambian Dalasi" },
  { code: "LYD", name: "Libyan Dinar" },
  { code: "IQD", name: "Iraqi Dinar" },
  { code: "GNF", name: "Guinean Franc" },
  { code: "MVR", name: "Maldivian Rufiyaa" },
  { code: "MGA", name: "Malagasy Ariary" },
  { code: "SVC", name: "Salvadoran Colón" },
  { code: "BTN", name: "Bhutanese Ngultrum" },
  { code: "AWG", name: "Aruban Florin" }
];
